<?php
/**
 * Todos os textos da aplicação em quatro idiomas. Cada chave tem a lista [pt, en, es, fr], por esta ordem.
 * Os %s são preenchidos por t('chave', valor1, valor2…).
 */

declare(strict_types=1);

if (!defined('APP')) {
    http_response_code(403);
    exit;
}

return [
    // ----- geral -----
    'escola'      => ["Colégio Horizonte", "Horizonte School", "Colegio Horizonte", "Collège Horizonte"],
    'ano_letivo'  => ["Ano letivo %s", "School year %s", "Curso %s", "Année scolaire %s"],
    'versao'      => ["Versão", "Version", "Versión", "Version"],
    'idioma'      => ["Idioma", "Language", "Idioma", "Langue"],
    'menu'        => ["Menu", "Menu", "Menú", "Menu"],
    'sair'        => ["Sair", "Log out", "Salir", "Se déconnecter"],
    'ola'         => ["Olá, %s", "Hello, %s", "Hola, %s", "Bonjour, %s"],
    'guardar'     => ["Guardar", "Save", "Guardar", "Enregistrer"],
    'cancelar'    => ["Cancelar", "Cancel", "Cancelar", "Annuler"],
    'apagar'      => ["Apagar", "Delete", "Borrar", "Supprimer"],
    'editar'      => ["Editar", "Edit", "Editar", "Modifier"],
    'abrir'       => ["Abrir", "Open", "Abrir", "Ouvrir"],
    'ver'         => ["Ver", "View", "Ver", "Voir"],
    'ver_todos'   => ["Ver todos", "See all", "Ver todos", "Tout voir"],
    'ver_tabela'  => ["Ver tabela de valores", "Show table of values", "Ver tabla de valores", "Voir le tableau des valeurs"],
    'filtrar'     => ["Filtrar", "Filter", "Filtrar", "Filtrer"],
    'procurar'    => ["Procurar", "Search", "Buscar", "Rechercher"],
    'todas'       => ["Todas", "All", "Todas", "Toutes"],
    'imprimir'    => ["Imprimir", "Print", "Imprimir", "Imprimer"],
    'duplicar'    => ["Duplicar", "Duplicate", "Duplicar", "Dupliquer"],
    'opcional'    => ["opcional", "optional", "opcional", "facultatif"],
    'voltar_inicio' => ["Voltar ao início", "Back to the start", "Volver al inicio", "Retour à l'accueil"],
    'voltar_lista'  => ["Voltar à lista", "Back to the list", "Volver a la lista", "Retour à la liste"],
    'nome'        => ["Nome", "Name", "Nombre", "Nom"],
    'email'       => ["Email", "Email", "Correo electrónico", "E-mail"],
    'password'    => ["Palavra-passe", "Password", "Contraseña", "Mot de passe"],
    'perfil'      => ["Perfil", "Profile", "Perfil", "Profil"],
    'data'        => ["Data", "Date", "Fecha", "Date"],
    'estado'      => ["Estado", "Status", "Estado", "Statut"],
    'ativo'       => ["Ativo", "Active", "Activo", "Actif"],
    'inativo'     => ["Inativo", "Inactive", "Inactivo", "Inactif"],
    'ativar'      => ["Ativar", "Activate", "Activar", "Activer"],
    'desativar'   => ["Desativar", "Deactivate", "Desactivar", "Désactiver"],
    'mensagem'    => ["Mensagem", "Message", "Mensaje", "Message"],
    'titulo'      => ["Título", "Title", "Título", "Titre"],
    'tipo'        => ["Tipo", "Type", "Tipo", "Type"],
    'peso'        => ["Peso", "Weight", "Peso", "Poids"],
    'ano'         => ["Ano", "Year", "Año", "Année"],
    'numero'      => ["Número", "Number", "Número", "Numéro"],
    'numero_abrev'=> ["N.º", "No.", "N.º", "N°"],
    'nascimento'  => ["Data de nascimento", "Date of birth", "Fecha de nacimiento", "Date de naissance"],
    'hora'        => ["Hora", "Time", "Hora", "Heure"],
    'n_resultados'=> ["%s resultados", "%s results", "%s resultados", "%s résultats"],

    // ----- perfis e menu -----
    'perfil_aluno'      => ["Aluno", "Student", "Alumno", "Élève"],
    'perfil_professor'  => ["Professor", "Teacher", "Profesor", "Professeur"],
    'perfil_secretaria' => ["Secretaria", "Administration", "Secretaría", "Secrétariat"],
    'perfil_direcao'    => ["Direção", "Principal's office", "Dirección", "Direction"],
    'menu_painel'       => ["Painel", "Dashboard", "Panel", "Tableau de bord"],
    'menu_notas'        => ["Lançar notas", "Enter grades", "Registrar notas", "Saisir les notes"],
    'menu_pauta'        => ["Pauta", "Grade sheet", "Acta de notas", "Relevé de notes"],
    'menu_relatorio'    => ["Relatório", "Report", "Informe", "Rapport"],
    'menu_boletim'      => ["Boletim", "Report card", "Boletín", "Bulletin"],
    'menu_faltas'       => ["Faltas", "Absences", "Faltas", "Absences"],
    'menu_avisos'       => ["Avisos", "Notices", "Avisos", "Annonces"],
    'menu_horario'      => ["Horário", "Timetable", "Horario", "Emploi du temps"],
    'menu_alunos'       => ["Alunos", "Students", "Alumnos", "Élèves"],
    'menu_professores'  => ["Professores", "Teachers", "Profesores", "Professeurs"],
    'menu_turmas'       => ["Turmas", "Classes", "Clases", "Classes"],
    'menu_direcao'      => ["Painel da direção", "Principal's dashboard", "Panel de dirección", "Tableau de la direction"],
    'menu_perfil'       => ["A minha conta", "My account", "Mi cuenta", "Mon compte"],

    // ----- erros e mensagens do sistema -----
    'erro_csrf'        => ["Pedido inválido (código de segurança em falta). Volte atrás e tente de novo.", "Invalid request (missing security code). Go back and try again.", "Solicitud no válida (falta el código de seguridad). Vuelva atrás e inténtelo de nuevo.", "Requête invalide (code de sécurité manquant). Revenez en arrière et réessayez."],
    'erro_titulo'      => ["Algo correu mal", "Something went wrong", "Algo salió mal", "Une erreur s'est produite"],
    'erro_texto'       => ["Não foi possível concluir o pedido. Tente outra vez dentro de instantes.", "The request could not be completed. Please try again in a moment.", "No se pudo completar la solicitud. Inténtelo de nuevo en unos instantes.", "La requête n'a pas pu aboutir. Réessayez dans un instant."],
    'erro_404_titulo'  => ["Página não encontrada", "Page not found", "Página no encontrada", "Page introuvable"],
    'erro_404_texto'   => ["Esta página não existe.", "This page does not exist.", "Esta página no existe.", "Cette page n'existe pas."],
    'erro_403_titulo'  => ["Sem acesso", "No access", "Sin acceso", "Accès refusé"],
    'erro_403_texto'   => ["O seu perfil não tem acesso a esta página.", "Your profile does not have access to this page.", "Su perfil no tiene acceso a esta página.", "Votre profil n'a pas accès à cette page."],
    'dados_invalidos'  => ["Dados inválidos. Verifique os campos e tente de novo.", "Invalid data. Check the fields and try again.", "Datos no válidos. Revise los campos e inténtelo de nuevo.", "Données invalides. Vérifiez les champs et réessayez."],
    'dados_guardados'  => ["Dados guardados.", "Data saved.", "Datos guardados.", "Données enregistrées."],
    'sem_permissao_turma' => ["Não tem permissão para esta turma e disciplina.", "You do not have permission for this class and subject.", "No tiene permiso para esta clase y asignatura.", "Vous n'avez pas l'autorisation pour cette classe et cette matière."],

    // ----- entrada -----
    'entrar'          => ["Entrar", "Sign in", "Entrar", "Se connecter"],
    'entrar_como'     => ["Entrar como %s", "Sign in as %s", "Entrar como %s", "Se connecter en tant que %s"],
    'login_subtitulo' => ["Sistema de gestão escolar", "School management system", "Sistema de gestión escolar", "Système de gestion scolaire"],
    'login_invalido'  => ["Email ou palavra-passe incorretos.", "Wrong email or password.", "Correo o contraseña incorrectos.", "E-mail ou mot de passe incorrect."],
    'login_bloqueado' => ["Demasiadas tentativas. Espere 30 segundos e tente de novo.", "Too many attempts. Wait 30 seconds and try again.", "Demasiados intentos. Espere 30 segundos e inténtelo de nuevo.", "Trop de tentatives. Attendez 30 secondes et réessayez."],
    'demo_titulo'     => ["Experimentar a demonstração", "Try the demo", "Probar la demostración", "Essayer la démonstration"],
    'demo_texto'      => ["Escolha um perfil para explorar. Todas as contas de demonstração usam a palavra-passe %s.", "Pick a profile to explore. All demo accounts use the password %s.", "Elija un perfil para explorar. Todas las cuentas de demostración usan la contraseña %s.", "Choisissez un profil à explorer. Tous les comptes de démonstration utilisent le mot de passe %s."],
    'demo_aviso'      => ["Colégio fictício, dados de exemplo.", "Fictional school, sample data.", "Colegio ficticio, datos de ejemplo.", "Collège fictif, données d'exemple."],

    // ----- painel -----
    'turma'                 => ["Turma", "Class", "Clase", "Classe"],
    'turmas'                => ["Turmas", "Classes", "Clases", "Classes"],
    'alunos'                => ["Alunos", "Students", "Alumnos", "Élèves"],
    'aluno'                 => ["Aluno", "Student", "Alumno", "Élève"],
    'professores'           => ["Professores", "Teachers", "Profesores", "Professeurs"],
    'professor'             => ["Professor", "Teacher", "Profesor", "Professeur"],
    'disciplina'            => ["Disciplina", "Subject", "Asignatura", "Matière"],
    'disciplinas'           => ["Disciplinas", "Subjects", "Asignaturas", "Matières"],
    'media_geral_p1'        => ["Média geral (1.º período)", "Overall average (term 1)", "Media general (1.er trimestre)", "Moyenne générale (1er trimestre)"],
    'negativas'             => ["Negativas", "Fails", "Suspensos", "Échecs"],
    'faltas_injustificadas' => ["Faltas injustificadas", "Unexcused absences", "Faltas injustificadas", "Absences injustifiées"],
    'turmas_que_leciona'    => ["Turmas que leciona", "Classes you teach", "Clases que imparte", "Classes enseignées"],
    'avaliacoes_por_lancar' => ["Avaliações por lançar", "Assessments to grade", "Evaluaciones por calificar", "Évaluations à noter"],
    'relatorios_guardados'  => ["Relatórios guardados", "Saved reports", "Informes guardados", "Rapports enregistrés"],
    'aulas_hoje'            => ["Aulas de hoje", "Today's lessons", "Clases de hoy", "Cours d'aujourd'hui"],
    'proximas_aulas'        => ["Próximas aulas", "Next lessons", "Próximas clases", "Prochains cours"],
    'fim_de_semana'         => ["Hoje não há aulas. Bom fim de semana!", "No lessons today. Enjoy the weekend!", "Hoy no hay clases. ¡Buen fin de semana!", "Pas de cours aujourd'hui. Bon week-end !"],
    'sem_aulas_hoje'        => ["Hoje não tem aulas.", "You have no lessons today.", "Hoy no tiene clases.", "Vous n'avez pas cours aujourd'hui."],
    'ver_horarios_texto'    => ["Consulte o horário de qualquer turma ou professor.", "See the timetable of any class or teacher.", "Consulte el horario de cualquier clase o profesor.", "Consultez l'emploi du temps de n'importe quelle classe ou professeur."],
    'sem_avisos'            => ["Não há avisos.", "There are no notices.", "No hay avisos.", "Aucune annonce."],
    'notas_recentes'        => ["Notas recentes", "Recent grades", "Notas recientes", "Notes récentes"],
    'avaliacao'             => ["Avaliação", "Assessment", "Evaluación", "Évaluation"],
    'nota'                  => ["Nota", "Grade", "Nota", "Note"],
    'as_minhas_turmas'      => ["As minhas turmas", "My classes", "Mis clases", "Mes classes"],
    'lancar_notas'          => ["Lançar notas", "Enter grades", "Registrar notas", "Saisir les notes"],

    // ----- notas -----
    'turma_disciplina'      => ["Turma e disciplina", "Class and subject", "Clase y asignatura", "Classe et matière"],
    'periodo'               => ["Período", "Term", "Periodo", "Période"],
    'periodo_n'             => ["%s.º período", "Term %s", "%s.º trimestre", "Trimestre %s"],
    'sem_lecionacao'        => ["Não há turmas disponíveis.", "There are no classes available.", "No hay clases disponibles.", "Aucune classe disponible."],
    'avaliacoes'            => ["Avaliações", "Assessments", "Evaluaciones", "Évaluations"],
    'sem_avaliacoes'        => ["Ainda não há avaliações neste período. Crie a primeira ao lado.", "There are no assessments in this term yet. Create the first one.", "Aún no hay evaluaciones en este periodo. Cree la primera.", "Pas encore d'évaluations ce trimestre. Créez la première."],
    'soma_pesos'            => ["Soma dos pesos", "Total weight", "Suma de los pesos", "Total des poids"],
    'aviso_soma_pesos'      => ["Os pesos devem somar 100%. A média usa só as avaliações com nota lançada.", "Weights should add up to 100%. The average only uses assessments that have a grade.", "Los pesos deben sumar 100%. La media solo usa las evaluaciones con nota.", "Les poids doivent totaliser 100 %. La moyenne n'utilise que les évaluations notées."],
    'nova_avaliacao'        => ["Nova avaliação", "New assessment", "Nueva evaluación", "Nouvelle évaluation"],
    'exemplo_teste'         => ["Ex.: Teste 2", "E.g. Test 2", "Ej.: Examen 2", "Ex. : Test 2"],
    'tipo_teste'            => ["Teste", "Test", "Examen", "Test"],
    'tipo_trabalho'         => ["Trabalho", "Project", "Trabajo", "Travail"],
    'tipo_participacao'     => ["Participação", "Participation", "Participación", "Participation"],
    'criar_avaliacao'       => ["Criar avaliação", "Create assessment", "Crear evaluación", "Créer l'évaluation"],
    'avaliacao_criada'      => ["Avaliação criada.", "Assessment created.", "Evaluación creada.", "Évaluation créée."],
    'avaliacao_apagada'     => ["Avaliação apagada.", "Assessment deleted.", "Evaluación borrada.", "Évaluation supprimée."],
    'avaliacao_invalida'    => ["Indique um título e um peso entre 1 e 100.", "Enter a title and a weight between 1 and 100.", "Indique un título y un peso entre 1 y 100.", "Indiquez un titre et un poids entre 1 et 100."],
    'confirmar_apagar_avaliacao' => ["Apagar esta avaliação e todas as suas notas?", "Delete this assessment and all its grades?", "¿Borrar esta evaluación y todas sus notas?", "Supprimer cette évaluation et toutes ses notes ?"],
    'ajuda_lancar_notas'    => ["Notas de 0 a 20 (pode usar vírgula). Deixe vazio para não ter nota. A média atualiza enquanto escreve.", "Grades from 0 to 20 (decimals allowed). Leave empty for no grade. The average updates as you type.", "Notas de 0 a 20 (puede usar coma). Déjelo vacío si no hay nota. La media se actualiza mientras escribe.", "Notes de 0 à 20 (virgule acceptée). Laissez vide s'il n'y a pas de note. La moyenne se met à jour pendant la saisie."],
    'media'                 => ["Média", "Average", "Media", "Moyenne"],
    'nota_final'            => ["Nota final", "Final grade", "Nota final", "Note finale"],
    'guardar_notas'         => ["Guardar notas", "Save grades", "Guardar notas", "Enregistrer les notes"],
    'ver_pauta'             => ["Ver pauta", "View grade sheet", "Ver acta", "Voir le relevé"],
    'notas_guardadas'       => ["Notas guardadas.", "Grades saved.", "Notas guardadas.", "Notes enregistrées."],
    'notas_invalidas'       => ["%s notas inválidas ignoradas (use valores de 0 a 20).", "%s invalid grades ignored (use values from 0 to 20).", "%s notas no válidas ignoradas (use valores de 0 a 20).", "%s notes invalides ignorées (valeurs de 0 à 20)."],

    // ----- pauta e boletim -----
    'pauta_titulo'          => ["Pauta de avaliação", "Grade sheet", "Acta de evaluación", "Relevé d'évaluation"],
    'sem_alunos'            => ["Não há alunos.", "There are no students.", "No hay alumnos.", "Aucun élève."],
    'resultado'             => ["Resultado", "Result", "Resultado", "Résultat"],
    'positiva'              => ["Positiva", "Pass", "Aprobado", "Réussite"],
    'negativa'              => ["Negativa", "Fail", "Suspenso", "Échec"],
    'positivas'             => ["Positivas", "Passes", "Aprobados", "Réussites"],
    'media_turma'           => ["Média da turma", "Class average", "Media de la clase", "Moyenne de la classe"],
    'assinatura_professor'  => ["O professor", "The teacher", "El profesor", "Le professeur"],
    'assinatura_direcao'    => ["A direção", "The principal", "La dirección", "La direction"],
    'boletim_titulo'        => ["Boletim de notas", "Report card", "Boletín de notas", "Bulletin de notes"],
    'media_anual'           => ["Média anual", "Yearly average", "Media anual", "Moyenne annuelle"],
    'media_geral'           => ["Média geral", "Overall average", "Media general", "Moyenne générale"],
    'faltas'                => ["Faltas", "Absences", "Faltas", "Absences"],
    'injustificadas_n'      => ["%s injustificadas", "%s unexcused", "%s injustificadas", "%s injustifiées"],
    'nota_rodape_boletim'   => ["Escala de 0 a 20. Nota positiva: %s ou mais.", "Scale from 0 to 20. Passing grade: %s or more.", "Escala de 0 a 20. Nota positiva: %s o más.", "Échelle de 0 à 20. Note de réussite : %s ou plus."],
    'assinatura_diretor_turma' => ["O diretor de turma", "The class teacher", "El tutor de la clase", "Le professeur principal"],
    'assinatura_encarregado'   => ["O encarregado de educação", "The parent or guardian", "El padre, madre o tutor", "Le responsable légal"],

    // ----- faltas -----
    'justificadas'          => ["Justificadas", "Excused", "Justificadas", "Justifiées"],
    'injustificadas'        => ["Injustificadas", "Unexcused", "Injustificadas", "Injustifiées"],
    'justificada'           => ["Justificada", "Excused", "Justificada", "Justifiée"],
    'injustificada'         => ["Injustificada", "Unexcused", "Injustificada", "Injustifiée"],
    'sem_faltas'            => ["Não há faltas.", "There are no absences.", "No hay faltas.", "Aucune absence."],
    'motivo'                => ["Motivo", "Reason", "Motivo", "Motif"],
    'motivo_omissao'        => ["Justificada pela secretaria", "Excused by the office", "Justificada por secretaría", "Justifiée par le secrétariat"],
    'aviso_faltas_risco'    => ["Atenção: tem %s ou mais faltas injustificadas.", "Warning: you have %s or more unexcused absences.", "Atención: tiene %s o más faltas injustificadas.", "Attention : vous avez %s absences injustifiées ou plus."],
    'registar_faltas'       => ["Registar faltas", "Record absences", "Registrar faltas", "Enregistrer les absences"],
    'ajuda_faltas'          => ["Marque os alunos que faltaram a esta aula. Desmarcar apaga a falta.", "Tick the students who were absent from this lesson. Unticking removes the absence.", "Marque a los alumnos que faltaron a esta clase. Desmarcar borra la falta.", "Cochez les élèves absents à ce cours. Décocher supprime l'absence."],
    'guardar_faltas'        => ["Guardar faltas", "Save absences", "Guardar faltas", "Enregistrer les absences"],
    'faltas_guardadas'      => ["Faltas guardadas.", "Absences saved.", "Faltas guardadas.", "Absences enregistrées."],
    'data_futura'           => ["Não pode registar faltas numa data futura.", "You cannot record absences on a future date.", "No puede registrar faltas en una fecha futura.", "Impossible d'enregistrer des absences à une date future."],
    'alunos_em_risco_faltas'=> ["Alunos com %s ou mais faltas injustificadas", "Students with %s or more unexcused absences", "Alumnos con %s o más faltas injustificadas", "Élèves avec %s absences injustifiées ou plus"],
    'so_injustificadas'     => ["Só injustificadas", "Unexcused only", "Solo injustificadas", "Injustifiées seulement"],
    'justificar'            => ["Justificar", "Excuse", "Justificar", "Justifier"],
    'anular_justificacao'   => ["Anular justificação", "Remove excuse", "Anular justificación", "Annuler la justification"],
    'falta_justificada'     => ["Falta justificada.", "Absence excused.", "Falta justificada.", "Absence justifiée."],
    'justificacao_anulada'  => ["Justificação anulada.", "Excuse removed.", "Justificación anulada.", "Justification annulée."],

    // ----- avisos -----
    'novo_aviso'            => ["Novo aviso", "New notice", "Nuevo aviso", "Nouvelle annonce"],
    'para'                  => ["Para", "To", "Para", "Pour"],
    'publicar'              => ["Publicar", "Publish", "Publicar", "Publier"],
    'para_todos'            => ["Todos", "Everyone", "Todos", "Tout le monde"],
    'para_alunos'           => ["Alunos", "Students", "Alumnos", "Élèves"],
    'para_professores'      => ["Professores", "Teachers", "Profesores", "Professeurs"],
    'para_secretaria'       => ["Secretaria", "Administration", "Secretaría", "Secrétariat"],
    'para_turma'            => ["Turma %s", "Class %s", "Clase %s", "Classe %s"],
    'aviso_invalido'        => ["Preencha o título, a mensagem e o destinatário.", "Fill in the title, the message and the recipient.", "Complete el título, el mensaje y el destinatario.", "Renseignez le titre, le message et le destinataire."],
    'aviso_publicado'       => ["Aviso publicado.", "Notice published.", "Aviso publicado.", "Annonce publiée."],
    'aviso_apagado'         => ["Aviso apagado.", "Notice deleted.", "Aviso borrado.", "Annonce supprimée."],
    'confirmar_apagar_aviso'=> ["Apagar este aviso?", "Delete this notice?", "¿Borrar este aviso?", "Supprimer cette annonce ?"],

    // ----- horário -----
    'horario_de'            => ["Horário de", "Timetable of", "Horario de", "Emploi du temps de"],
    'almoco'                => ["Almoço", "Lunch", "Almuerzo", "Déjeuner"],
    'dia_1'                 => ["Segunda", "Monday", "Lunes", "Lundi"],
    'dia_2'                 => ["Terça", "Tuesday", "Martes", "Mardi"],
    'dia_3'                 => ["Quarta", "Wednesday", "Miércoles", "Mercredi"],
    'dia_4'                 => ["Quinta", "Thursday", "Jueves", "Jeudi"],
    'dia_5'                 => ["Sexta", "Friday", "Viernes", "Vendredi"],
    'sala_turma'            => ["Sala da turma", "Home room", "Aula de la clase", "Salle de classe"],
    'sala_pavilhao'         => ["Pavilhão", "Sports hall", "Pabellón", "Gymnase"],
    'sala_laboratorio'      => ["Laboratório", "Laboratory", "Laboratorio", "Laboratoire"],

    // ----- gestão de alunos, professores e turmas -----
    'editar_aluno'          => ["Editar aluno", "Edit student", "Editar alumno", "Modifier l'élève"],
    'novo_aluno'            => ["Novo aluno", "New student", "Nuevo alumno", "Nouvel élève"],
    'criar_conta'           => ["Criar conta", "Create account", "Crear cuenta", "Créer le compte"],
    'ajuda_nova_conta'      => ["Se deixar o email vazio, é criado um automaticamente. A palavra-passe inicial aparece uma única vez.", "If you leave the email empty one is created for you. The initial password is shown only once.", "Si deja el correo vacío, se crea uno automáticamente. La contraseña inicial se muestra una sola vez.", "Si l'e-mail est vide, il est créé automatiquement. Le mot de passe initial n'apparaît qu'une seule fois."],
    'conta_criada'          => ["Conta criada: %s · palavra-passe inicial: %s (só aparece agora).", "Account created: %s · initial password: %s (shown only now).", "Cuenta creada: %s · contraseña inicial: %s (solo se muestra ahora).", "Compte créé : %s · mot de passe initial : %s (affiché une seule fois)."],
    'password_reposta'      => ["Nova palavra-passe de %s: %s (só aparece agora).", "New password for %s: %s (shown only now).", "Nueva contraseña de %s: %s (solo se muestra ahora).", "Nouveau mot de passe de %s : %s (affiché une seule fois)."],
    'repor_password'        => ["Repor palavra-passe", "Reset password", "Restablecer contraseña", "Réinitialiser le mot de passe"],
    'confirmar_repor_password' => ["Gerar uma nova palavra-passe para esta conta?", "Generate a new password for this account?", "¿Generar una nueva contraseña para esta cuenta?", "Générer un nouveau mot de passe pour ce compte ?"],
    'email_invalido'        => ["O email não é válido.", "The email is not valid.", "El correo no es válido.", "L'e-mail n'est pas valide."],
    'email_existe'          => ["Já existe uma conta com esse email.", "An account with that email already exists.", "Ya existe una cuenta con ese correo.", "Un compte avec cet e-mail existe déjà."],
    'conta_desativada'      => ["Conta desativada.", "Account deactivated.", "Cuenta desactivada.", "Compte désactivé."],
    'conta_ativada'         => ["Conta ativada.", "Account activated.", "Cuenta activada.", "Compte activé."],
    'conta_demo_protegida'  => ["As contas de demonstração não podem ser alteradas.", "Demo accounts cannot be changed.", "Las cuentas de demostración no se pueden modificar.", "Les comptes de démonstration ne peuvent pas être modifiés."],
    'leciona'               => ["Leciona", "Teaches", "Imparte", "Enseigne"],
    'novo_professor'        => ["Novo professor", "New teacher", "Nuevo profesor", "Nouveau professeur"],
    'atribuir_disciplina'   => ["Atribuir disciplina a uma turma", "Assign a subject to a class", "Asignar asignatura a una clase", "Attribuer une matière à une classe"],
    'atribuir'              => ["Atribuir", "Assign", "Asignar", "Attribuer"],
    'ajuda_atribuir'        => ["Se a turma já tinha professor nessa disciplina, é substituído.", "If the class already had a teacher for that subject, they are replaced.", "Si la clase ya tenía profesor en esa asignatura, se sustituye.", "Si la classe avait déjà un professeur pour cette matière, il est remplacé."],
    'atribuicao_guardada'   => ["Atribuição guardada.", "Assignment saved.", "Asignación guardada.", "Attribution enregistrée."],
    'professor_com_aulas'   => ["Este professor ainda leciona turmas. Atribua essas disciplinas a outro professor primeiro.", "This teacher still teaches classes. Assign those subjects to another teacher first.", "Este profesor aún imparte clases. Asigne esas asignaturas a otro profesor primero.", "Ce professeur enseigne encore des classes. Attribuez d'abord ces matières à un autre professeur."],
    'nova_turma'            => ["Nova turma", "New class", "Nueva clase", "Nouvelle classe"],
    'criar_turma'           => ["Criar turma", "Create class", "Crear clase", "Créer la classe"],
    'ajuda_nova_turma'      => ["Depois de criar a turma, atribua os professores na página Professores.", "After creating the class, assign teachers on the Teachers page.", "Después de crear la clase, asigne los profesores en la página Profesores.", "Après avoir créé la classe, attribuez les professeurs dans la page Professeurs."],
    'turma_criada'          => ["Turma criada.", "Class created.", "Clase creada.", "Classe créée."],
    'turma_existe'          => ["Já existe uma turma com esse nome.", "A class with that name already exists.", "Ya existe una clase con ese nombre.", "Une classe portant ce nom existe déjà."],
    'turma_apagada'         => ["Turma apagada.", "Class deleted.", "Clase borrada.", "Classe supprimée."],
    'turma_com_alunos'      => ["Não se pode apagar uma turma com alunos. Mude os alunos de turma primeiro.", "A class with students cannot be deleted. Move the students first.", "No se puede borrar una clase con alumnos. Cambie primero a los alumnos de clase.", "Impossible de supprimer une classe avec des élèves. Déplacez d'abord les élèves."],
    'confirmar_apagar_turma'=> ["Apagar esta turma?", "Delete this class?", "¿Borrar esta clase?", "Supprimer cette classe ?"],
    'ver_alunos'            => ["Ver alunos", "View students", "Ver alumnos", "Voir les élèves"],

    // ----- painel da direção -----
    'media_geral_escola'    => ["Média geral da escola", "School average", "Media general del colegio", "Moyenne générale de l'école"],
    'alunos_sem_negativas'  => ["Alunos sem negativas", "Students with no fails", "Alumnos sin suspensos", "Élèves sans échec"],
    'alunos_em_risco'       => ["Alunos em risco", "Students at risk", "Alumnos en riesgo", "Élèves à risque"],
    'media_por_turma'       => ["Média por turma", "Average by class", "Media por clase", "Moyenne par classe"],
    'media_por_disciplina'  => ["Média por disciplina", "Average by subject", "Media por asignatura", "Moyenne par matière"],
    'legenda_escala'        => ["Escala de 0 a 20. A linha marca a nota positiva (%s).", "Scale from 0 to 20. The line marks the passing grade (%s).", "Escala de 0 a 20. La línea marca la nota de aprobado (%s).", "Échelle de 0 à 20. La ligne marque la note de réussite (%s)."],
    'resultados_alunos'     => ["Resultados dos alunos", "Student results", "Resultados de los alumnos", "Résultats des élèves"],
    'legenda_rosca'         => ["1.º período: alunos com e sem negativas.", "Term 1: students with and without fails.", "1.er trimestre: alumnos con y sin suspensos.", "1er trimestre : élèves avec et sans échec."],
    'sem_negativas'         => ["Sem negativas", "No fails", "Sin suspensos", "Sans échec"],
    'com_negativas'         => ["Com negativas", "With fails", "Con suspensos", "Avec échecs"],
    'criterio_risco'        => ["Em risco: 2 ou mais negativas, ou %s ou mais faltas injustificadas.", "At risk: 2 or more fails, or %s or more unexcused absences.", "En riesgo: 2 o más suspensos, o %s o más faltas injustificadas.", "À risque : 2 échecs ou plus, ou %s absences injustifiées ou plus."],
    'sem_risco'             => ["Nenhum aluno em risco.", "No students at risk.", "Ningún alumno en riesgo.", "Aucun élève à risque."],
    'repor_demonstracao'    => ["Repor a demonstração", "Reset the demo", "Restablecer la demostración", "Réinitialiser la démonstration"],
    'repor_texto'           => ["Apaga todas as alterações e volta aos dados de exemplo originais. Termina a sessão.", "Removes all changes and goes back to the original sample data. Ends your session.", "Borra todos los cambios y vuelve a los datos de ejemplo originales. Cierra la sesión.", "Supprime toutes les modifications et revient aux données d'exemple d'origine. Termine la session."],
    'repor_botao'           => ["Repor dados de exemplo", "Reset sample data", "Restablecer datos de ejemplo", "Réinitialiser les données d'exemple"],
    'confirmar_repor_demo'  => ["Repor todos os dados de exemplo? As alterações feitas serão perdidas.", "Reset all sample data? Any changes you made will be lost.", "¿Restablecer todos los datos de ejemplo? Se perderán los cambios realizados.", "Réinitialiser toutes les données d'exemple ? Les modifications seront perdues."],

    // ----- a minha conta -----
    'os_meus_dados'         => ["Os meus dados", "My details", "Mis datos", "Mes informations"],
    'mudar_password'        => ["Mudar palavra-passe", "Change password", "Cambiar contraseña", "Changer le mot de passe"],
    'password_atual'        => ["Palavra-passe atual", "Current password", "Contraseña actual", "Mot de passe actuel"],
    'password_nova'         => ["Nova palavra-passe (mínimo 8 caracteres)", "New password (at least 8 characters)", "Nueva contraseña (mínimo 8 caracteres)", "Nouveau mot de passe (8 caractères minimum)"],
    'password_confirmar'    => ["Repetir a nova palavra-passe", "Repeat the new password", "Repetir la nueva contraseña", "Répéter le nouveau mot de passe"],
    'perfil_demo_bloqueada' => ["As contas de demonstração não podem mudar de palavra-passe.", "Demo accounts cannot change their password.", "Las cuentas de demostración no pueden cambiar de contraseña.", "Les comptes de démonstration ne peuvent pas changer de mot de passe."],
    'perfil_atual_errada'   => ["A palavra-passe atual está errada.", "The current password is wrong.", "La contraseña actual es incorrecta.", "Le mot de passe actuel est incorrect."],
    'perfil_curta'          => ["A nova palavra-passe deve ter pelo menos 8 caracteres.", "The new password must have at least 8 characters.", "La nueva contraseña debe tener al menos 8 caracteres.", "Le nouveau mot de passe doit avoir au moins 8 caractères."],
    'perfil_diferentes'     => ["As duas palavras-passe novas não são iguais.", "The two new passwords do not match.", "Las dos contraseñas nuevas no coinciden.", "Les deux nouveaux mots de passe ne correspondent pas."],
    'perfil_alterada'       => ["Palavra-passe alterada.", "Password changed.", "Contraseña cambiada.", "Mot de passe modifié."],

    // ----- disciplinas -----
    'disc_port' => ["Português", "Portuguese", "Portugués", "Portugais"],
    'disc_mat'  => ["Matemática", "Mathematics", "Matemáticas", "Mathématiques"],
    'disc_ing'  => ["Inglês", "English", "Inglés", "Anglais"],
    'disc_cn'   => ["Ciências Naturais", "Natural Sciences", "Ciencias Naturales", "Sciences naturelles"],
    'disc_hist' => ["História", "History", "Historia", "Histoire"],
    'disc_ef'   => ["Educação Física", "Physical Education", "Educación Física", "Éducation physique"],
    'disc_geo'  => ["Geografia", "Geography", "Geografía", "Géographie"],
    'disc_tic'  => ["TIC", "ICT", "TIC", "TIC"],

    // ----- relatório (pauta livre em PDF) -----
    'relatorio_intro'       => ["Crie pautas com os seus próprios alunos, colunas e notas e descarregue-as em PDF. Os relatórios são só seus.", "Create grade sheets with your own students, columns and grades and download them as PDF. Reports are private to you.", "Cree actas con sus propios alumnos, columnas y notas y descárguelas en PDF. Los informes son solo suyos.", "Créez des relevés avec vos propres élèves, colonnes et notes et téléchargez-les en PDF. Les rapports sont privés."],
    'os_meus_relatorios'    => ["Os meus relatórios", "My reports", "Mis informes", "Mes rapports"],
    'sem_relatorios'        => ["Ainda não tem relatórios. Crie um novo ao lado.", "You have no reports yet. Create one on the right.", "Aún no tiene informes. Cree uno al lado.", "Vous n'avez pas encore de rapports. Créez-en un."],
    'atualizado'            => ["Atualizado", "Updated", "Actualizado", "Mis à jour"],
    'novo_relatorio'        => ["Novo relatório", "New report", "Nuevo informe", "Nouveau rapport"],
    'novo_em_branco'        => ["Começar em branco", "Start blank", "Empezar en blanco", "Commencer à vide"],
    'novo_em_branco_texto'  => ["Escreva os nomes, defina as colunas de notas e preencha como quiser.", "Type the names, define the grade columns and fill it in your own way.", "Escriba los nombres, defina las columnas de notas y rellene como quiera.", "Saisissez les noms, définissez les colonnes de notes et remplissez à votre guise."],
    'importar_turma'        => ["Criar a partir de uma turma", "Create from a class", "Crear a partir de una clase", "Créer à partir d'une classe"],
    'importar_texto'        => ["Copia os alunos e as notas já lançadas. Depois pode editar tudo à vontade, sem mexer nas notas da escola.", "Copies the students and the grades already entered. You can then edit everything freely without touching the school's grades.", "Copia los alumnos y las notas ya registradas. Después puede editar todo sin tocar las notas del colegio.", "Copie les élèves et les notes déjà saisies. Vous pouvez ensuite tout modifier sans toucher aux notes de l'école."],
    'importar'              => ["Criar relatório", "Create report", "Crear informe", "Créer le rapport"],
    'relatorio_importado'   => ["Relatório criado a partir da turma.", "Report created from the class.", "Informe creado a partir de la clase.", "Rapport créé à partir de la classe."],
    'relatorio_guardado'    => ["Relatório guardado.", "Report saved.", "Informe guardado.", "Rapport enregistré."],
    'relatorio_apagado'     => ["Relatório apagado.", "Report deleted.", "Informe borrado.", "Rapport supprimé."],
    'relatorio_duplicado'   => ["Relatório duplicado.", "Report duplicated.", "Informe duplicado.", "Rapport dupliqué."],
    'relatorio_nao_encontrado' => ["Relatório não encontrado.", "Report not found.", "Informe no encontrado.", "Rapport introuvable."],
    'relatorio_titulo_vazio'=> ["Indique um título para o relatório.", "Enter a title for the report.", "Indique un título para el informe.", "Indiquez un titre pour le rapport."],
    'relatorio_nome_vazio'  => ["Há linhas com notas mas sem nome de aluno.", "Some rows have grades but no student name.", "Hay filas con notas pero sin nombre de alumno.", "Certaines lignes ont des notes mais pas de nom d'élève."],
    'confirmar_apagar_relatorio' => ["Apagar este relatório?", "Delete this report?", "¿Borrar este informe?", "Supprimer ce rapport ?"],
    'copia_de'              => ["Cópia de %s", "Copy of %s", "Copia de %s", "Copie de %s"],
    'dados_relatorio'       => ["Dados do relatório", "Report details", "Datos del informe", "Informations du rapport"],
    'titulo_relatorio'      => ["Título do relatório", "Report title", "Título del informe", "Titre du rapport"],
    'instituicao'           => ["Instituição", "Institution", "Institución", "Établissement"],
    'curso_turma'           => ["Curso ou turma", "Course or class", "Curso o clase", "Cours ou classe"],
    'disciplina_modulo'     => ["Disciplina ou módulo", "Subject or module", "Asignatura o módulo", "Matière ou module"],
    'formador'              => ["Professor ou formador", "Teacher or trainer", "Profesor o formador", "Professeur ou formateur"],
    'tabela_notas'          => ["Tabela de notas", "Grade table", "Tabla de notas", "Tableau de notes"],
    'ajuda_editor'          => ["Escreva diretamente nas células. Enter passa ao aluno seguinte. Médias e resultados calculam-se sozinhos (nota positiva: 10 ou mais).", "Type directly in the cells. Enter moves to the next student. Averages and results calculate themselves (passing grade: 10 or more).", "Escriba directamente en las celdas. Enter pasa al alumno siguiente. Las medias y los resultados se calculan solos (aprobado: 10 o más).", "Saisissez directement dans les cellules. Entrée passe à l'élève suivant. Les moyennes et résultats se calculent seuls (réussite : 10 ou plus)."],
    'nome_aluno'            => ["Nome do aluno", "Student name", "Nombre del alumno", "Nom de l'élève"],
    'titulo_coluna'         => ["Título da coluna", "Column title", "Título de la columna", "Titre de la colonne"],
    'remover_coluna'        => ["Remover coluna", "Remove column", "Quitar columna", "Supprimer la colonne"],
    'remover_aluno'         => ["Remover aluno", "Remove student", "Quitar alumno", "Supprimer l'élève"],
    'adicionar_aluno'       => ["Adicionar aluno", "Add student", "Añadir alumno", "Ajouter un élève"],
    'adicionar_coluna'      => ["Adicionar coluna", "Add column", "Añadir columna", "Ajouter une colonne"],
    'limpar_notas'          => ["Limpar todas as notas", "Clear all grades", "Borrar todas las notas", "Effacer toutes les notes"],
    'confirmar_limpar_notas'=> ["Apagar todas as notas desta tabela? Os nomes e as colunas ficam.", "Clear all grades in this table? Names and columns stay.", "¿Borrar todas las notas de esta tabla? Los nombres y las columnas se mantienen.", "Effacer toutes les notes de ce tableau ? Les noms et les colonnes restent."],
    'limite_atingido'       => ["Limite atingido.", "Limit reached.", "Límite alcanzado.", "Limite atteinte."],
    'observacoes'           => ["Observações", "Notes", "Observaciones", "Observations"],
    'guardar_e_baixar'      => ["Guardar e baixar PDF", "Save and download PDF", "Guardar y descargar PDF", "Enregistrer et télécharger le PDF"],
    'baixar_ultimo_pdf'     => ["Baixar PDF guardado", "Download saved PDF", "Descargar PDF guardado", "Télécharger le PDF enregistré"],
    'pdf_a_descarregar'     => ["O PDF está a ser descarregado.", "Your PDF is downloading.", "Se está descargando el PDF.", "Votre PDF est en cours de téléchargement."],
    'pdf_clique_aqui'       => ["Se não começar, clique aqui.", "If it does not start, click here.", "Si no empieza, haga clic aquí.", "S'il ne démarre pas, cliquez ici."],
    'assinatura_formador'   => ["O professor ou formador", "The teacher or trainer", "El profesor o formador", "Le professeur ou formateur"],
    'gerado_em'             => ["Gerado em %s", "Generated on %s", "Generado el %s", "Généré le %s"],
    'pagina_de'             => ["Página %s de %s", "Page %s of %s", "Página %s de %s", "Page %s sur %s"],
];
